/**
 * Mascot art, by screen.
 *
 * The board pairs a different pose with each screen — the mascot is not one
 * image — so screens ask for their screen, not for "the mascot". The files
 * live in design/mascot/ and are required straight from there rather than
 * copied into src/: a second copy of a final asset is the exact failure mode
 * that produced the wrong mascot art once already (docs/decision-log.md).
 *
 * Poses are added as their screens are built. design/mascot/ and its README
 * are generated by `node scripts/copy-mascot.mjs`, so a new board export is a
 * one-command update — but the names below change with it, because the board's
 * asset UUIDs are not stable across exports.
 */

export const mascot = {
  /** 2.1 SPLASH — the full-body pose under the logo. */
  splash: require('../../design/mascot/02-chunk-mascot.png'),
  /** 2.2 WELCOME — the waving pose, and the mascot proper. */
  waving: require('../../design/mascot/03-chunk-mascot-waving.png'),
  /** 2.3 GOALS — the small bust beside the speech bubble. */
  goals: require('../../design/mascot/04-chunk.png'),
  /** 2.4 NAME + GRADE. */
  name: require('../../design/mascot/05-chunk.png'),
  /** 2.6 STUDY STYLE. */
  studyStyle: require('../../design/mascot/06-chunk.png'),
  /** 2.7 YOUR WEEK. */
  week: require('../../design/mascot/07-chunk.png'),
  /** 2.8 WHEN YOU START. */
  whenYouStart: require('../../design/mascot/08-chunk.png'),
  /** 2.9 WHAT GOES WRONG. */
  whatGoesWrong: require('../../design/mascot/09-chunk.png'),
  /** 2.14 BUILDING YOUR PLAN. */
  building: require('../../design/mascot/10-chunk-working.png'),
  /** 2.15 YOUR FIRST PLAN. */
  firstPlan: require('../../design/mascot/11-chunk.png'),
  /** 2.16 PAYWALL. */
  paywall: require('../../design/mascot/12-chunk-waving-with-checklist-calendar-and-star.png'),
  /** 2.17 LOG IN. */
  login: require('../../design/mascot/13-chunk-mascot.png'),
  /**
   * 2.18 LOG IN — EMAIL: the pointing pose with the blue arrow.
   *
   * The README maps this file to 3.1 HOME, because 2.18 is not in the 19 Sep
   * export the README was generated from. The newer board uses the same pose
   * on both. Re-run `scripts/copy-mascot.mjs` when that export lands — the
   * UUIDs, and so the numbers, will move.
   */
  email: require('../../design/mascot/14-chunk.png'),
  /**
   * 2.19 LOG IN — VERIFY: the winking pose behind the magnifying glass.
   *
   * The README maps this file to 4.1 SCAN TO CHUNK for the same reason
   * `email` above is mapped to 3.1 — 2.19 postdates the export.
   */
  verify: require('../../design/mascot/20-chunk.png'),
  /** 3.1 HOME — the pose inside the orange CHUNK SAYS card. */
  home: require('../../design/mascot/14-chunk.png'),
  /** 3.2 TODAY — PATH: the climber at the foot of the path. */
  today: require('../../design/mascot/15-chunk.png'),
  /** 3.3 FOCUS — RUNNING. */
  focus: require('../../design/mascot/16-chunk-studying.png'),
  /** 3.4 CHUNK COMPLETE. */
  complete: require('../../design/mascot/17-chunk-cheering.png'),
  /** 3.7 THE CHUNKING MOMENT — the bust beside the speech bubble. */
  chunked: require('../../design/mascot/19-chunk.png'),
  /** 4.1 SCAN TO CHUNK. */
  scan: require('../../design/mascot/20-chunk.png'),
  /** 4.2 ASK CHUNK — three poses on the one frame. */
  ask: require('../../design/mascot/21-chunk.png'),
  askReply: require('../../design/mascot/22-chunk.png'),
  askThinking: require('../../design/mascot/23-chunk.png'),
  /** 4.3 STUDY MODES. */
  studyModes: require('../../design/mascot/24-chunk.png'),
  /** 4.4 QUIZ. */
  quiz: require('../../design/mascot/25-chunk.png'),
  /** 4.5 QUIZ RESULT. */
  quizResult: require('../../design/mascot/26-chunk-cheering.png'),
  /** 5.1 PROGRESS — inside the orange THIS WEEK card. */
  progress: require('../../design/mascot/27-chunk.png'),
  /** 5.3 EMPTY STATE. */
  waiting: require('../../design/mascot/28-chunk-waiting.png'),
  /** 5.4 URGENT DEADLINE — inside the AFTER THAT card. */
  urgent: require('../../design/mascot/29-chunk.png'),
} as const;

// 2.10 DAILY PACE, 2.11 WITH CHUNK VS ALONE, 2.12 YOUR PROGRESS CURVE and
// 2.13 IMPORT WORK draw no mascot at all.

export type MascotPose = keyof typeof mascot;
