#!/usr/bin/env node
/**
 * Copy the board's mascot art into design/mascot/ under readable names.
 *
 * Run `node scripts/extract-board.mjs` first — this reads its output. The
 * board pairs a different pose with each screen, so each file is named for the
 * screen that follows it in document order, which is how the board itself
 * associates them.
 *
 * Re-runnable: it rewrites design/mascot/ from scratch, so a new board export
 * with new asset UUIDs is a one-command update rather than a manual copy.
 */
import { readFileSync, writeFileSync, rmSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const extracted = join(root, 'design', 'extracted');
const outDir = join(root, 'design', 'mascot');

const html = readFileSync(join(extracted, 'board.html'), 'utf8');

/** Every <img> and every screen label, in the order they appear. */
const tokens = [];
const imgRe = /<img[^>]*src="([0-9a-f-]{36})"[^>]*alt="([^"]*)"[^>]*>/g;
const labelRe = /letter-spacing:\.08em">((?:\d+\.\d+[a-z]?|[A-Z][\w.]*) [^<]{2,40})<\/div>/g;

for (const m of html.matchAll(imgRe)) tokens.push({ kind: 'img', at: m.index, uuid: m[1], alt: m[2] });
for (const m of html.matchAll(labelRe)) tokens.push({ kind: 'label', at: m.index, text: m[1].trim() });
tokens.sort((a, b) => a.at - b.at);

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 52) || 'mascot';

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const rows = [];
let index = 0;
for (let i = 0; i < tokens.length; i++) {
  const t = tokens[i];
  if (t.kind !== 'img') continue;
  // The screen this pose belongs to is the next label after it.
  const label = tokens.slice(i + 1).find((x) => x.kind === 'label');
  const src = join(extracted, `${t.uuid}.png`);
  if (!existsSync(src)) continue;

  const name = `${String(index).padStart(2, '0')}-${slug(t.alt)}.png`;
  copyFileSync(src, join(outDir, name));
  rows.push({ name, alt: t.alt, screen: label ? label.text : '(unlabelled)', uuid: t.uuid });
  index++;
}

const readme = [
  '# Mascot art',
  '',
  'Generated by `node scripts/copy-mascot.mjs` from `design/extracted/`, which',
  'comes from `design/board.html`. Do not edit by hand and do not take mascot',
  'art from anywhere else.',
  '',
  'The board uses **a different pose per screen** — the mascot is not one image.',
  'Each row is named for the screen that follows it in the board, which is how',
  'the board itself pairs them.',
  '',
  '| file | alt text on the board | screen |',
  '|---|---|---|',
  ...rows.map((r) => `| \`${r.name}\` | ${r.alt} | ${r.screen} |`),
  '',
].join('\n');
writeFileSync(join(outDir, 'README.md'), readme);

console.log(`mascot: ${rows.length} poses -> design/mascot/`);
